// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hermes.Models;

public partial class CallForSpeaker
{
    /// <summary>
    /// The identifier of the call for speaker.
    /// </summary>
    public int CallForSpeakerId { get; set; }

    public string Permalink { get; set; }

    /// <summary>
    /// The identifier of the call for speaker status.
    /// </summary>
    public int CallForSpeakerStatusId { get; set; }

    /// <summary>
    /// The name of the event.
    /// </summary>
    public string EventName { get; set; }

    /// <summary>
    /// The URL of the event.
    /// </summary>
    public string EventUrl { get; set; }

    /// <summary>
    /// The start date of the event.
    /// </summary>
    public DateOnly EventStartDate { get; set; }

    /// <summary>
    /// The end date of the event.
    /// </summary>
    public DateOnly EventEndDate { get; set; }

    /// <summary>
    /// The location of the event.
    /// </summary>
    public string EventLocation { get; set; }

    /// <summary>
    /// The city where the event is located.
    /// </summary>
    public string EventCity { get; set; }

    /// <summary>
    /// The ISO 3166-1 alpha-2 country code where the event is located.
    /// </summary>
    public string EventCountryCode { get; set; }

    /// <summary>
    /// The ISO 3166-2 alpha-3 country division code where the event is located.
    /// </summary>
    public string EventCountryDivisionCode { get; set; }

    /// <summary>
    /// The identifier of the time zone where the event is located.
    /// </summary>
    public string EventTimeZoneId { get; set; }

    /// <summary>
    /// The URL of the call for speaker.
    /// </summary>
    public string CallForSpeakerUrl { get; set; }

    /// <summary>
    /// The start date of the call for speaker.
    /// </summary>
    public DateOnly? CallForSpeakerStartDate { get; set; }

    /// <summary>
    /// The end date of the call for speaker.
    /// </summary>
    public DateOnly? CallForSpeakerEndDate { get; set; }

    /// <summary>
    /// The expected decision date for the submissions.
    /// </summary>
    public DateOnly? ExpectedDecisionDate { get; set; }

    /// <summary>
    /// Indicates if the speaker will receive a honorarium.
    /// </summary>
    public bool SpeakerHonorarium { get; set; }

    /// <summary>
    /// The amount of the honorarium.
    /// </summary>
    public decimal? SpeakerHonorariumAmount { get; set; }

    /// <summary>
    /// The currency of the honorarium.
    /// </summary>
    public string SpeakerHonorariumCurrency { get; set; }

    /// <summary>
    /// Additional notes about the honorarium.
    /// </summary>
    public string SpeakerHonorariumNotes { get; set; }

    /// <summary>
    /// Indicates if the event will cover the travel expenses of the speaker.
    /// </summary>
    public bool TravelExpensesCovered { get; set; }

    /// <summary>
    /// Additional notes about the travel expenses.
    /// </summary>
    public string TravelNotes { get; set; }

    /// <summary>
    /// Indicates if the event will cover the accomodation expenses of the speaker.
    /// </summary>
    public bool AccomodationExpensesCovered { get; set; }

    /// <summary>
    /// Additional notes about the accomodation expenses.
    /// </summary>
    public string AccomodationNotes { get; set; }

    /// <summary>
    /// Indicates if the event will cover the fee of the speaker.
    /// </summary>
    public bool EventFeeCovered { get; set; }

    /// <summary>
    /// Additional notes about the event fee.
    /// </summary>
    public string EventFeeNotes { get; set; }

    /// <summary>
    /// The maximum number of submissions allowed.
    /// </summary>
    public int? SubmissionLimit { get; set; }

    public virtual CallForSpeakerStatus CallForSpeakerStatus { get; set; }

    public virtual CountryDivision CountryDivision { get; set; }

    public virtual Country EventCountryCodeNavigation { get; set; }

    public virtual TimeZone EventTimeZone { get; set; }

    public virtual ICollection<Submission> Submissions { get; set; } = new List<Submission>();
}