// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hermes.Models;

/// <summary>
/// Lookup table representing the countries as defined by the ISO 3166-1 standard.
/// </summary>
public partial class Country
{
    /// <summary>
    /// Identifier of the country using the ISO 3166-1 Alpha-2 code.
    /// </summary>
    public string CountryCode { get; set; }

    /// <summary>
    /// Name of the country using the ISO 3166-1 Country Name.
    /// </summary>
    public string CountryName { get; set; }

    /// <summary>
    /// Identifier of the world region where the country is located.
    /// </summary>
    public string WorldRegionCode { get; set; }

    /// <summary>
    /// Identifier of the country using the United Nations M49 standard.
    /// </summary>
    public string M49code { get; set; }

    /// <summary>
    /// Flag indicating whether the country has divisions (states, provinces, etc.)
    /// </summary>
    public bool HasDivisions { get; set; }

    /// <summary>
    /// The primary name of the country&apos;s divisions.
    /// </summary>
    public string DivisionName { get; set; }

    /// <summary>
    /// Flag indicating whether the country record is enabled.
    /// </summary>
    public bool IsEnabled { get; set; }

    public virtual ICollection<CallForSpeaker> CallForSpeakers { get; set; } = new List<CallForSpeaker>();

    public virtual ICollection<CountryDivision> CountryDivisions { get; set; } = new List<CountryDivision>();

    public virtual WorldRegion WorldRegionCodeNavigation { get; set; }
}