// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hermes.Models;

public partial class DownloadType
{
    /// <summary>
    /// The identifier of the download type record.
    /// </summary>
    public int DownloadTypeId { get; set; }

    /// <summary>
    /// The name of the download type.
    /// </summary>
    public string DownloadTypeName { get; set; }

    /// <summary>
    /// A description of the download type.
    /// </summary>
    public string TypeDescription { get; set; }

    /// <summary>
    /// The sorting order of the download type.
    /// </summary>
    public int SortOrder { get; set; }

    /// <summary>
    /// Flag indicating whether the download type is enabled.
    /// </summary>
    public bool IsEnabled { get; set; }

    public virtual ICollection<EngagementPresentationDownload> EngagementPresentationDownloads { get; set; } = new List<EngagementPresentationDownload>();
}