// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hermes.Models;

public partial class EngagementPresentation
{
    /// <summary>
    /// The identifier of the engagement presentation record.
    /// </summary>
    public int EngagementPresentationId { get; set; }

    /// <summary>
    /// The identifier of the associated engagement.
    /// </summary>
    public string EngagementId { get; set; }

    /// <summary>
    /// The identifier of the associated presentation.
    /// </summary>
    public string PresentationId { get; set; }

    /// <summary>
    /// The identifier of the status of the engagement presentation.
    /// </summary>
    public int EngagementPresentationStatusId { get; set; }

    /// <summary>
    /// The date and time the engagement presentation starts.
    /// </summary>
    public DateTime? StartDateTime { get; set; }

    /// <summary>
    /// The length of the presentation in minutes.
    /// </summary>
    public int PresentationLength { get; set; }

    /// <summary>
    /// The room where the presentation will be held.
    /// </summary>
    public string Room { get; set; }

    /// <summary>
    /// The URL for the engagement presentation.
    /// </summary>
    public string EngagementPresentationUrl { get; set; }

    /// <summary>
    /// The language code for the presentation.
    /// </summary>
    public string LangaugeCode { get; set; }

    /// <summary>
    /// The full title of the presentation.
    /// </summary>
    public string PresentationTitle { get; set; }

    /// <summary>
    /// The short title of the presentation.
    /// </summary>
    public string PresentationShortTitle { get; set; }

    /// <summary>
    /// The full abstract for the presentation.
    /// </summary>
    public string Abstract { get; set; }

    /// <summary>
    /// The short abstract for the presentation.
    /// </summary>
    public string ShortAbstract { get; set; }

    /// <summary>
    /// The summary for the presentation.
    /// </summary>
    public string ElevatorPitch { get; set; }

    /// <summary>
    /// Additional details for the presentation.
    /// </summary>
    public string AdditionalDetails { get; set; }

    /// <summary>
    /// Flag indicating whether the engagement presentation is enabled.
    /// </summary>
    public bool IsEnabled { get; set; }

    public virtual Engagement Engagement { get; set; }

    public virtual ICollection<EngagementPresentationLearningObjective> EngagementPresentationLearningObjectives { get; set; } = new List<EngagementPresentationLearningObjective>();

    public virtual EngagementPresentationStatus EngagementPresentationStatus { get; set; }

    public virtual ICollection<EngagementPresentationTag> EngagementPresentationTags { get; set; } = new List<EngagementPresentationTag>();

    public virtual Presentation Presentation { get; set; }
}