// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hermes.Models;

/// <summary>
/// Represents a status of an engagement call for speakers.
/// </summary>
public partial class EngagementCallForSpeakerStatus
{
    /// <summary>
    /// The identifier of the engagement call for speakers status record.
    /// </summary>
    public int EngagementCallForSpeakerStatusId { get; set; }

    /// <summary>
    /// The name of the engagement call for speakers status.
    /// </summary>
    public string EngagementCallForSpeakerStatusName { get; set; }

    public string StatusDescription { get; set; }

    /// <summary>
    /// The order in which the engagement call for speakers status should be displayed.
    /// </summary>
    public int SortOrder { get; set; }

    /// <summary>
    /// Indicates whether the engagement call for speakers status is enabled.
    /// </summary>
    public bool IsEnabled { get; set; }

    /// <summary>
    /// Indicates whether the engagement call for speakers status is the default status.
    /// </summary>
    public bool IsDefault { get; set; }
}