// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hermes.Models;

/// <summary>
/// Represents a status of an engagement.
/// </summary>
public partial class EngagementStatus
{
    /// <summary>
    /// The identifier of the engagement status record.
    /// </summary>
    public int EngagementStatusId { get; set; }

    /// <summary>
    /// The name of the engagement status.
    /// </summary>
    public string EngagementStatusName { get; set; }

    /// <summary>
    /// A description of the engagement status.
    /// </summary>
    public string StatusDescription { get; set; }

    /// <summary>
    /// The sorting order of the engagement status.
    /// </summary>
    public int SortOrder { get; set; }

    /// <summary>
    /// Flag indicating whether the engagement status is enabled.
    /// </summary>
    public bool IsEnabled { get; set; }

    public virtual ICollection<Engagement> Engagements { get; set; } = new List<Engagement>();
}