// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hermes.Models;

/// <summary>
/// Represents a type of an engagement.
/// </summary>
public partial class EngagementType
{
    /// <summary>
    /// The identifier of the engagement type record.
    /// </summary>
    public int EngagementTypeId { get; set; }

    /// <summary>
    /// The name of the engagement type.
    /// </summary>
    public string EngagementTypeName { get; set; }

    /// <summary>
    /// A description of the engagement type.
    /// </summary>
    public string TypeDescription { get; set; }

    /// <summary>
    /// The sorting order of the engagement type.
    /// </summary>
    public int SortOrder { get; set; }

    /// <summary>
    /// Flag indicating whether the engagement type is enabled.
    /// </summary>
    public bool IsEnabled { get; set; }

    public virtual ICollection<Engagement> Engagements { get; set; } = new List<Engagement>();
}