// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hermes.Models;

/// <summary>
/// Represents a status of an engagement presentation.
/// </summary>
public partial class EngagementPresentationStatus
{
    /// <summary>
    /// The identifier of the engagement presentation status record.
    /// </summary>
    public int EngagementPresentationStatusId { get; set; }

    /// <summary>
    /// The name of the engagement presentation status.
    /// </summary>
    public string EngagementPresentationStatusName { get; set; }

    /// <summary>
    /// A description of the engagement presentation status.
    /// </summary>
    public string StatusDescription { get; set; }

    /// <summary>
    /// Flag indicating whether the engagement presentation status should be included on the website.
    /// </summary>
    public bool IncludeOnWebsite { get; set; }

    /// <summary>
    /// The sorting order of the engagement presentation status.
    /// </summary>
    public int SortOrder { get; set; }

    /// <summary>
    /// Flag indicating whether the engagement presentation status is enabled.
    /// </summary>
    public bool IsEnabled { get; set; }

    public virtual ICollection<EngagementPresentation> EngagementPresentations { get; set; } = new List<EngagementPresentation>();
}