// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hermes.Models;

public partial class EngagementPresentationDownload
{
    /// <summary>
    /// The identifier of the engagement presentation download record.
    /// </summary>
    public int EngagementPresentationDownloadId { get; set; }

    /// <summary>
    /// The identifier of the engagement presentation record.
    /// </summary>
    public int EngagementPresentationId { get; set; }

    /// <summary>
    /// The identifier of the download type.
    /// </summary>
    public int DownloadTypeId { get; set; }

    /// <summary>
    /// The name of the download.
    /// </summary>
    public string DownloadName { get; set; }

    /// <summary>
    /// The path to the download.
    /// </summary>
    public string DownloadPath { get; set; }

    /// <summary>
    /// Flag indicating whether the download is enabled.
    /// </summary>
    public bool IsEnabled { get; set; }

    public virtual DownloadType DownloadType { get; set; }

    public virtual EngagementPresentation EngagementPresentation { get; set; }
}