// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hermes.Models;

/// <summary>
/// Represents a learning objective of an engagement presentation.
/// </summary>
public partial class EngagementPresentationLearningObjective
{
    /// <summary>
    /// The identifier of the engagement presentation learning objective record.
    /// </summary>
    public int EngagementPresentationLearningObjectiveId { get; set; }

    /// <summary>
    /// The identifier of the engagement presentation.
    /// </summary>
    public int EngagementPresentationId { get; set; }

    /// <summary>
    /// The text of the learning objective.
    /// </summary>
    public string LearningObjectiveText { get; set; }

    /// <summary>
    /// The sorting order of the learning objective.
    /// </summary>
    public int SortOrder { get; set; }

    public virtual EngagementPresentation EngagementPresentation { get; set; }
}