// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hermes.Models;

public partial class EngagementCallForSpeker
{
    /// <summary>
    /// The permalink of the engagement.
    /// </summary>
    public string EngagementPermalink { get; set; }

    public int EngagementCallForSpeakerStatusId { get; set; }

    /// <summary>
    /// The URL of the call for speakers.
    /// </summary>
    public string CallForSpeakersUrl { get; set; }

    /// <summary>
    /// The start date of the call for speakers.
    /// </summary>
    public DateOnly StartDate { get; set; }

    /// <summary>
    /// The end date of the call for speakers.
    /// </summary>
    public DateOnly EndDate { get; set; }

    /// <summary>
    /// The expected decision date for the call for speakers.
    /// </summary>
    public DateOnly? ExpectedDecisionDate { get; set; }

    /// <summary>
    /// The actual decision date for the call for speakers.
    /// </summary>
    public DateOnly? ActualDecisionDate { get; set; }

    /// <summary>
    /// Indicates if a speaker honorarium is offered.
    /// </summary>
    public bool SpeakerHonorarium { get; set; }

    /// <summary>
    /// The amount of the speaker honorarium.
    /// </summary>
    public decimal? SpeakerHonorariumAmount { get; set; }

    /// <summary>
    /// The currency of the speaker honorarium.
    /// </summary>
    public string SpeakerHonorariumCurrency { get; set; }

    /// <summary>
    /// Additional notes about the speaker honorarium.
    /// </summary>
    public string SpeakerHonorariumNotes { get; set; }

    /// <summary>
    /// Indicates if travel expenses are covered for speakers.
    /// </summary>
    public bool TravelExpensesCovered { get; set; }

    /// <summary>
    /// Additional notes about travel expenses for speakers.
    /// </summary>
    public string TravelExpensesNotes { get; set; }

    /// <summary>
    /// Indicates if accommodation is covered for speakers.
    /// </summary>
    public bool AccommodationCovered { get; set; }

    /// <summary>
    /// Additional notes about accommodation for speakers.
    /// </summary>
    public string AccommodationNotes { get; set; }

    /// <summary>
    /// Indicates if event fees are covered for speakers.
    /// </summary>
    public bool EventFeeCovered { get; set; }

    /// <summary>
    /// Additional notes about event fees for speakers.
    /// </summary>
    public string EventFeeNotes { get; set; }

    /// <summary>
    /// The maximum number of submissions allowed per speaker.
    /// </summary>
    public int SubmissionLimit { get; set; }

    public virtual Engagement EngagementPermalinkNavigation { get; set; }
}