// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hermes.Models;

/// <summary>
/// Associates a tag with an engagement presentation.
/// </summary>
public partial class EngagementPresentationTag
{
    /// <summary>
    /// The identifier of the engagement presentation tag record.
    /// </summary>
    public int EngagementPresentationTagId { get; set; }

    /// <summary>
    /// The identifier of the engagement presentation.
    /// </summary>
    public int EngagementPresentationId { get; set; }

    /// <summary>
    /// The identifier of the associated tag.
    /// </summary>
    public int TagId { get; set; }

    public virtual EngagementPresentation EngagementPresentation { get; set; }

    public virtual Tag Tag { get; set; }
}