// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Hermes.Models;

public partial class HermesContext : DbContext
{
    public HermesContext(DbContextOptions<HermesContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Country> Countries { get; set; }

    public virtual DbSet<CountryDivision> CountryDivisions { get; set; }

    public virtual DbSet<Engagement> Engagements { get; set; }

    public virtual DbSet<EngagementCallForSpeaker> EngagementCallForSpeakers { get; set; }

    public virtual DbSet<EngagementCallForSpeakerStatus> EngagementCallForSpeakerStatuses { get; set; }

    public virtual DbSet<EngagementPresentation> EngagementPresentations { get; set; }

    public virtual DbSet<EngagementPresentationLearningObjective> EngagementPresentationLearningObjectives { get; set; }

    public virtual DbSet<EngagementPresentationStatus> EngagementPresentationStatuses { get; set; }

    public virtual DbSet<EngagementPresentationTag> EngagementPresentationTags { get; set; }

    public virtual DbSet<EngagementStatus> EngagementStatuses { get; set; }

    public virtual DbSet<EngagementType> EngagementTypes { get; set; }

    public virtual DbSet<Language> Languages { get; set; }

    public virtual DbSet<LearningObjective> LearningObjectives { get; set; }

    public virtual DbSet<Presentation> Presentations { get; set; }

    public virtual DbSet<PresentationStatus> PresentationStatuses { get; set; }

    public virtual DbSet<PresentationTag> PresentationTags { get; set; }

    public virtual DbSet<PresentationText> PresentationTexts { get; set; }

    public virtual DbSet<PresentationType> PresentationTypes { get; set; }

    public virtual DbSet<Tag> Tags { get; set; }

    public virtual DbSet<TimeZone> TimeZones { get; set; }

    public virtual DbSet<WorldRegion> WorldRegions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Country>(entity =>
        {
            entity.HasKey(e => e.CountryCode).HasName("pkcCountry");

            entity.ToTable("Country", tb => tb.HasComment("Lookup table representing the countries as defined by the ISO 3166-1 standard."));

            entity.HasIndex(e => e.WorldRegionCode, "idxCountry_WorldRegionCode");

            entity.Property(e => e.CountryCode)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength()
                .HasComment("Identifier of the country using the ISO 3166-1 Alpha-2 code.");
            entity.Property(e => e.CountryName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasComment("Name of the country using the ISO 3166-1 Country Name.");
            entity.Property(e => e.DivisionName)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasComment("The primary name of the country's divisions.");
            entity.Property(e => e.HasDivisions).HasComment("Flag indicating whether the country has divisions (states, provinces, etc.)");
            entity.Property(e => e.IsEnabled).HasComment("Flag indicating whether the country record is enabled.");
            entity.Property(e => e.M49code)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength()
                .HasComment("Identifier of the country using the United Nations M49 standard.")
                .HasColumnName("M49Code");
            entity.Property(e => e.WorldRegionCode)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength()
                .HasComment("Identifier of the world region where the country is located.");

            entity.HasOne(d => d.WorldRegionCodeNavigation).WithMany(p => p.Countries)
                .HasForeignKey(d => d.WorldRegionCode)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fkCountry_WorldRegion");
        });

        modelBuilder.Entity<CountryDivision>(entity =>
        {
            entity.HasKey(e => new { e.CountryCode, e.CountryDivisionCode }).HasName("pkcCountryDivision");

            entity.ToTable("CountryDivision", tb => tb.HasComment("Lookup table representing the world regions as defined by the ISO 3166-2 standard."));

            entity.Property(e => e.CountryCode)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CountryDivisionCode)
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength()
                .HasComment("Identifier of the country division using the ISO 3166-2 Alpha-2 code.");
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasComment("The category name of the country division.");
            entity.Property(e => e.CountryDivisionName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasComment("Name of the country using the ISO 3166-2 Subdivision Name.");
            entity.Property(e => e.IsEnabled).HasComment("Flag indicating whether the country division record is enabled.");

            entity.HasOne(d => d.CountryCodeNavigation).WithMany(p => p.CountryDivisions)
                .HasForeignKey(d => d.CountryCode)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fkCountryDivision_Country");
        });

        modelBuilder.Entity<Engagement>(entity =>
        {
            entity.HasKey(e => e.Permalink).HasName("pkcEngagement");

            entity.ToTable("Engagement", tb => tb.HasComment("Represents an engagement."));

            entity.Property(e => e.Permalink)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasComment("The unique identifier for the engagement.");
            entity.Property(e => e.City)
                .IsRequired()
                .HasMaxLength(100)
                .HasComment("The city where the engagement is located.");
            entity.Property(e => e.CountryCode)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength()
                .HasComment("The country code for the engagement.");
            entity.Property(e => e.CountryDivisionCode)
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength()
                .HasComment("The country division code for the engagement.");
            entity.Property(e => e.EndDate).HasComment("The end date of the engagement.");
            entity.Property(e => e.EndingCost)
                .HasMaxLength(20)
                .HasComment("The ending cost of the engagement.");
            entity.Property(e => e.EngagementDescription)
                .HasMaxLength(2000)
                .HasComment("The description of the engagement.");
            entity.Property(e => e.EngagementName)
                .IsRequired()
                .HasMaxLength(200)
                .HasComment("The name of the engagement.");
            entity.Property(e => e.EngagementStatusId)
                .HasDefaultValue(1)
                .HasComment("The identifier of the engagement status.");
            entity.Property(e => e.EngagementSummary)
                .HasMaxLength(160)
                .HasComment("The summary of the engagement.");
            entity.Property(e => e.EngagementTypeId)
                .HasDefaultValue(1)
                .HasComment("The identifier of the engagement type.");
            entity.Property(e => e.EngagementUrl)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasComment("The URL of the engagement.");
            entity.Property(e => e.IncludeInPublicProfile)
                .HasDefaultValue(true)
                .HasComment("Flag indicating whether the engagement should be included in the public profile.");
            entity.Property(e => e.IsEnabled)
                .HasDefaultValue(true)
                .HasComment("Flag indicating whether the engagement is enabled.");
            entity.Property(e => e.IsPublic)
                .HasDefaultValue(true)
                .HasComment("Flag indicating whether the engagement is public.");
            entity.Property(e => e.IsVirtual).HasComment("Flag indicating whether the engagement is virtual.");
            entity.Property(e => e.LanguageCode)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.ListingLocation)
                .HasMaxLength(100)
                .HasComment("The location of the engagement as it should be listed.");
            entity.Property(e => e.OverviewLocation)
                .HasMaxLength(300)
                .HasComment("The location of the engagement.");
            entity.Property(e => e.StartDate).HasComment("The start date of the engagement.");
            entity.Property(e => e.StartingCost)
                .HasMaxLength(20)
                .HasComment("The starting cost of the engagement.");
            entity.Property(e => e.TimeZoneId)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasComment("The time zone of the engagement.");
            entity.Property(e => e.Venue)
                .HasMaxLength(200)
                .HasComment("The venue where the engagement is located.");

            entity.HasOne(d => d.CountryCodeNavigation).WithMany(p => p.Engagements)
                .HasForeignKey(d => d.CountryCode)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fkEngagement_Country");

            entity.HasOne(d => d.EngagementStatus).WithMany(p => p.Engagements)
                .HasForeignKey(d => d.EngagementStatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fkEngagement_EngagementStatus");

            entity.HasOne(d => d.EngagementType).WithMany(p => p.Engagements)
                .HasForeignKey(d => d.EngagementTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fkEngagement_EngagementType");

            entity.HasOne(d => d.LanguageCodeNavigation).WithMany(p => p.Engagements)
                .HasForeignKey(d => d.LanguageCode)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fkEngagement_Language");

            entity.HasOne(d => d.TimeZone).WithMany(p => p.Engagements)
                .HasForeignKey(d => d.TimeZoneId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fkEngagement_TimeZone");

            entity.HasOne(d => d.CountryDivision).WithMany(p => p.Engagements)
                .HasForeignKey(d => new { d.CountryCode, d.CountryDivisionCode })
                .HasConstraintName("fkEngagement_CountryDivision");
        });

        modelBuilder.Entity<EngagementCallForSpeaker>(entity =>
        {
            entity.HasKey(e => e.EngagementPermalink).HasName("pkcEngagementCallForSpekers");

            entity.ToTable("EngagementCallForSpeaker");

            entity.Property(e => e.EngagementPermalink)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasComment("The permalink of the engagement.");
            entity.Property(e => e.AccommodationCovered).HasComment("Indicates if accommodation is covered for speakers.");
            entity.Property(e => e.AccommodationNotes)
                .HasMaxLength(200)
                .HasComment("Additional notes about accommodation for speakers.");
            entity.Property(e => e.ActualDecisionDate).HasComment("The actual decision date for the call for speakers.");
            entity.Property(e => e.CallForSpeakersUrl)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasComment("The URL of the call for speakers.");
            entity.Property(e => e.EndDate).HasComment("The end date of the call for speakers.");
            entity.Property(e => e.EventFeeCovered).HasComment("Indicates if event fees are covered for speakers.");
            entity.Property(e => e.EventFeeNotes)
                .HasMaxLength(200)
                .HasComment("Additional notes about event fees for speakers.");
            entity.Property(e => e.ExpectedDecisionDate).HasComment("The expected decision date for the call for speakers.");
            entity.Property(e => e.SpeakerHonorarium).HasComment("Indicates if a speaker honorarium is offered.");
            entity.Property(e => e.SpeakerHonorariumAmount)
                .HasComment("The amount of the speaker honorarium.")
                .HasColumnType("decimal(10, 2)");
            entity.Property(e => e.SpeakerHonorariumCurrency)
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength()
                .HasComment("The currency of the speaker honorarium.");
            entity.Property(e => e.SpeakerHonorariumNotes)
                .HasMaxLength(200)
                .HasComment("Additional notes about the speaker honorarium.");
            entity.Property(e => e.StartDate).HasComment("The start date of the call for speakers.");
            entity.Property(e => e.SubmissionLimit)
                .HasDefaultValue(-1)
                .HasComment("The maximum number of submissions allowed per speaker.");
            entity.Property(e => e.TravelExpensesCovered).HasComment("Indicates if travel expenses are covered for speakers.");
            entity.Property(e => e.TravelExpensesNotes)
                .HasMaxLength(200)
                .HasComment("Additional notes about travel expenses for speakers.");

            entity.HasOne(d => d.EngagementCallForSpeakerStatus).WithMany(p => p.EngagementCallForSpeakers)
                .HasForeignKey(d => d.EngagementCallForSpeakerStatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fkEngagementCallForSpekers_EngagementCallForSpeakerStatus");

            entity.HasOne(d => d.EngagementPermalinkNavigation).WithOne(p => p.EngagementCallForSpeaker)
                .HasForeignKey<EngagementCallForSpeaker>(d => d.EngagementPermalink)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fkEngagementCallForSpekers_Engagement");
        });

        modelBuilder.Entity<EngagementCallForSpeakerStatus>(entity =>
        {
            entity.HasKey(e => e.EngagementCallForSpeakerStatusId).HasName("pkcEngagementCallForSpeakerStatus");

            entity.ToTable("EngagementCallForSpeakerStatus", tb => tb.HasComment("Represents a status of an engagement call for speakers."));

            entity.Property(e => e.EngagementCallForSpeakerStatusId)
                .ValueGeneratedNever()
                .HasComment("The identifier of the engagement call for speakers status record.");
            entity.Property(e => e.EngagementCallForSpeakerStatusName)
                .IsRequired()
                .HasMaxLength(50)
                .HasComment("The name of the engagement call for speakers status.");
            entity.Property(e => e.IsDefault).HasComment("Indicates whether the engagement call for speakers status is the default status.");
            entity.Property(e => e.IsEnabled).HasComment("Indicates whether the engagement call for speakers status is enabled.");
            entity.Property(e => e.SortOrder).HasComment("The order in which the engagement call for speakers status should be displayed.");
            entity.Property(e => e.StatusDescription).HasMaxLength(500);
        });

        modelBuilder.Entity<EngagementPresentation>(entity =>
        {
            entity.HasKey(e => e.EngagementPresentationId).HasName("pkcEngagementPresentation");

            entity.ToTable("EngagementPresentation");

            entity.Property(e => e.EngagementPresentationId).HasComment("The identifier of the engagement presentation record.");
            entity.Property(e => e.Abstract)
                .HasMaxLength(3000)
                .HasComment("The full abstract for the presentation.");
            entity.Property(e => e.AdditionalDetails)
                .HasMaxLength(3000)
                .HasComment("Additional details for the presentation.");
            entity.Property(e => e.ElevatorPitch)
                .HasMaxLength(300)
                .HasComment("The summary for the presentation.");
            entity.Property(e => e.EngagementId)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasComment("The identifier of the associated engagement.");
            entity.Property(e => e.EngagementPresentationStatusId)
                .HasDefaultValue(1)
                .HasComment("The identifier of the status of the engagement presentation.");
            entity.Property(e => e.EngagementPresentationUrl)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasComment("The URL for the engagement presentation.");
            entity.Property(e => e.IsEnabled)
                .HasDefaultValue(true)
                .HasComment("Flag indicating whether the engagement presentation is enabled.");
            entity.Property(e => e.LangaugeCode)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .HasDefaultValue("en")
                .IsFixedLength()
                .HasComment("The language code for the presentation.");
            entity.Property(e => e.PresentationId)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasComment("The identifier of the associated presentation.");
            entity.Property(e => e.PresentationLength).HasComment("The length of the presentation in minutes.");
            entity.Property(e => e.PresentationShortTitle)
                .HasMaxLength(60)
                .HasComment("The short title of the presentation.");
            entity.Property(e => e.PresentationTitle)
                .IsRequired()
                .HasMaxLength(300)
                .HasComment("The full title of the presentation.");
            entity.Property(e => e.Room)
                .HasMaxLength(100)
                .HasComment("The room where the presentation will be held.");
            entity.Property(e => e.ShortAbstract)
                .HasMaxLength(2000)
                .HasComment("The short abstract for the presentation.");
            entity.Property(e => e.StartDateTime).HasComment("The date and time the engagement presentation starts.");

            entity.HasOne(d => d.Engagement).WithMany(p => p.EngagementPresentations)
                .HasForeignKey(d => d.EngagementId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fkEngagementPresentation_Engagement");

            entity.HasOne(d => d.EngagementPresentationStatus).WithMany(p => p.EngagementPresentations)
                .HasForeignKey(d => d.EngagementPresentationStatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fkEngagementPresentation_EngagementPresentationStatus");

            entity.HasOne(d => d.Presentation).WithMany(p => p.EngagementPresentations)
                .HasForeignKey(d => d.PresentationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fkEngagementPresentation_Presentation");
        });

        modelBuilder.Entity<EngagementPresentationLearningObjective>(entity =>
        {
            entity.HasKey(e => e.EngagementPresentationLearningObjectiveId).HasName("pkcEngagementPresentationLearningObjective");

            entity.ToTable("EngagementPresentationLearningObjective", tb => tb.HasComment("Represents a learning objective of an engagement presentation."));

            entity.HasIndex(e => new { e.EngagementPresentationId, e.SortOrder }, "ucEngagementPresentationLearningObjective").IsUnique();

            entity.Property(e => e.EngagementPresentationLearningObjectiveId).HasComment("The identifier of the engagement presentation learning objective record.");
            entity.Property(e => e.EngagementPresentationId).HasComment("The identifier of the engagement presentation.");
            entity.Property(e => e.LearningObjectiveText)
                .IsRequired()
                .HasMaxLength(1000)
                .HasComment("The text of the learning objective.");
            entity.Property(e => e.SortOrder).HasComment("The sorting order of the learning objective.");

            entity.HasOne(d => d.EngagementPresentation).WithMany(p => p.EngagementPresentationLearningObjectives)
                .HasForeignKey(d => d.EngagementPresentationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fkEngagementPresentationLearningObjective_EngagementPresentation");
        });

        modelBuilder.Entity<EngagementPresentationStatus>(entity =>
        {
            entity.HasKey(e => e.EngagementPresentationStatusId).HasName("pkcEngagementPresentationStatus");

            entity.ToTable("EngagementPresentationStatus", tb => tb.HasComment("Represents a status of an engagement presentation."));

            entity.Property(e => e.EngagementPresentationStatusId)
                .ValueGeneratedNever()
                .HasComment("The identifier of the engagement presentation status record.");
            entity.Property(e => e.EngagementPresentationStatusName)
                .IsRequired()
                .HasMaxLength(100)
                .HasComment("The name of the engagement presentation status.");
            entity.Property(e => e.IncludeOnWebsite).HasComment("Flag indicating whether the engagement presentation status should be included on the website.");
            entity.Property(e => e.IsEnabled).HasComment("Flag indicating whether the engagement presentation status is enabled.");
            entity.Property(e => e.SortOrder).HasComment("The sorting order of the engagement presentation status.");
            entity.Property(e => e.StatusDescription)
                .HasMaxLength(500)
                .HasComment("A description of the engagement presentation status.");
        });

        modelBuilder.Entity<EngagementPresentationTag>(entity =>
        {
            entity.HasKey(e => e.EngagementPresentationTagId).HasName("pkcEngagementPresentationTag");

            entity.ToTable("EngagementPresentationTag", tb => tb.HasComment("Associates a tag with an engagement presentation."));

            entity.Property(e => e.EngagementPresentationTagId).HasComment("The identifier of the engagement presentation tag record.");
            entity.Property(e => e.EngagementPresentationId).HasComment("The identifier of the engagement presentation.");
            entity.Property(e => e.TagId).HasComment("The identifier of the associated tag.");

            entity.HasOne(d => d.EngagementPresentation).WithMany(p => p.EngagementPresentationTags)
                .HasForeignKey(d => d.EngagementPresentationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fkEngagementPresentationTag_EngagementPresentation");

            entity.HasOne(d => d.Tag).WithMany(p => p.EngagementPresentationTags)
                .HasForeignKey(d => d.TagId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fkEngagementPresentationTag_Tag");
        });

        modelBuilder.Entity<EngagementStatus>(entity =>
        {
            entity.HasKey(e => e.EngagementStatusId).HasName("pkcEngagementStatus");

            entity.ToTable("EngagementStatus", tb => tb.HasComment("Represents a status of an engagement."));

            entity.Property(e => e.EngagementStatusId)
                .ValueGeneratedNever()
                .HasComment("The identifier of the engagement status record.");
            entity.Property(e => e.DisplayOnWebsite).HasComment("Flag indicating whether the engagement status should be displayed on the website.");
            entity.Property(e => e.EngagementStatusName)
                .IsRequired()
                .HasMaxLength(100)
                .HasComment("The name of the engagement status.");
            entity.Property(e => e.IsEnabled).HasComment("Flag indicating whether the engagement status is enabled.");
            entity.Property(e => e.SortOrder).HasComment("The sorting order of the engagement status.");
            entity.Property(e => e.StatusDescription)
                .HasMaxLength(500)
                .HasComment("A description of the engagement status.");
        });

        modelBuilder.Entity<EngagementType>(entity =>
        {
            entity.HasKey(e => e.EngagementTypeId).HasName("pkcEngagementType");

            entity.ToTable("EngagementType", tb => tb.HasComment("Represents a type of an engagement."));

            entity.Property(e => e.EngagementTypeId)
                .ValueGeneratedNever()
                .HasComment("The identifier of the engagement type record.");
            entity.Property(e => e.EngagementTypeName)
                .IsRequired()
                .HasMaxLength(100)
                .HasComment("The name of the engagement type.");
            entity.Property(e => e.IsEnabled).HasComment("Flag indicating whether the engagement type is enabled.");
            entity.Property(e => e.SortOrder).HasComment("The sorting order of the engagement type.");
            entity.Property(e => e.TypeDescription)
                .HasMaxLength(500)
                .HasComment("A description of the engagement type.");
        });

        modelBuilder.Entity<Language>(entity =>
        {
            entity.HasKey(e => e.LanguageCode).HasName("pkcLangauge");

            entity.ToTable("Language", tb => tb.HasComment("Represents a spoken/written language."));

            entity.Property(e => e.LanguageCode)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength()
                .HasComment("Identifier of the language.");
            entity.Property(e => e.IsEnabled).HasComment("Flag indicating whether the language is enabled.");
            entity.Property(e => e.LanguageName)
                .IsRequired()
                .HasMaxLength(100)
                .HasComment("Name of the language.");
            entity.Property(e => e.NativeName)
                .IsRequired()
                .HasMaxLength(100)
                .HasComment("Native name of the language.");
        });

        modelBuilder.Entity<LearningObjective>(entity =>
        {
            entity.HasKey(e => e.LearningObjectiveId).HasName("pkcLearningObjective");

            entity.ToTable("LearningObjective", tb => tb.HasComment("Represents a learning objective of a presentation."));

            entity.HasIndex(e => new { e.PresentationTextId, e.SortOrder }, "ucLearningObjective").IsUnique();

            entity.Property(e => e.LearningObjectiveId).HasComment("The identifier of the learning objective record.");
            entity.Property(e => e.LearningObjectiveText)
                .IsRequired()
                .HasMaxLength(1000)
                .HasComment("The text of the learning objective.");
            entity.Property(e => e.PresentationTextId).HasComment("The identifier of the associated presentation (text) record.");
            entity.Property(e => e.SortOrder).HasComment("The sorting order of the learning objective.");

            entity.HasOne(d => d.PresentationText).WithMany(p => p.LearningObjectives)
                .HasForeignKey(d => d.PresentationTextId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fkLearningObjective_PresentationText");
        });

        modelBuilder.Entity<Presentation>(entity =>
        {
            entity.HasKey(e => e.Permalink).HasName("pkcPresentation");

            entity.ToTable("Presentation", tb => tb.HasComment("Represents the speaker's presentations."));

            entity.HasIndex(e => e.Permalink, "unqPresentation_Permalink").IsUnique();

            entity.Property(e => e.Permalink)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasComment("The permament link for the presentation.");
            entity.Property(e => e.DefaultLanguageCode)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .HasDefaultValue("en")
                .IsFixedLength()
                .HasComment("The default language to use for the presentation.");
            entity.Property(e => e.IncludeInPublicProfile)
                .HasDefaultValue(true)
                .HasComment("Flag indicating whether the presentation is to be include in the public profile.");
            entity.Property(e => e.IsArchived).HasComment("Flag indicating whether the presentation has been archived.");
            entity.Property(e => e.OriginalThumbnailUrl)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasComment("The original thumbnail image for the presentation.");
            entity.Property(e => e.PresentationStatusId)
                .HasDefaultValue(1)
                .HasComment("Identifier of the status of the presentation is represented.");
            entity.Property(e => e.PresentationTypeId).HasComment("Identifier of the type of presentation is represented.");
            entity.Property(e => e.PrivateRepoLink)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasComment("The link to the private repository for the presentation.");
            entity.Property(e => e.PublicRepoLink)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasComment("The link to the public repository for the presentation.");
            entity.Property(e => e.Resources)
                .HasMaxLength(3000)
                .HasComment("The resources for the presentation.");

            entity.HasOne(d => d.DefaultLanguageCodeNavigation).WithMany(p => p.Presentations)
                .HasForeignKey(d => d.DefaultLanguageCode)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fkPresentation_Language");

            entity.HasOne(d => d.PresentationStatus).WithMany(p => p.Presentations)
                .HasForeignKey(d => d.PresentationStatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fkPresentation_PresentationStatus");

            entity.HasOne(d => d.PresentationType).WithMany(p => p.Presentations)
                .HasForeignKey(d => d.PresentationTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fkPresentation_PresentationType");
        });

        modelBuilder.Entity<PresentationStatus>(entity =>
        {
            entity.HasKey(e => e.PresentationStatusId).HasName("pkcPresentationStatus");

            entity.ToTable("PresentationStatus", tb => tb.HasComment("Represents the status of a speaker's presentation."));

            entity.Property(e => e.PresentationStatusId)
                .ValueGeneratedNever()
                .HasComment("The identifier of the presentation status record.");
            entity.Property(e => e.IsEnabled).HasComment("Flag indicating whether the presentation status is enabled.");
            entity.Property(e => e.PresentationIsArchived).HasComment("Flag indicating whether the presentation status has been archived.");
            entity.Property(e => e.PresentationStatusName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("The name of the presentation status.");
            entity.Property(e => e.SortOrder).HasComment("The order in which the presentation status should be displayed.");
        });

        modelBuilder.Entity<PresentationTag>(entity =>
        {
            entity.HasKey(e => e.PresentationTagId).HasName("pkcPresentationTag");

            entity.ToTable("PresentationTag", tb => tb.HasComment("Represents the association between a presentation and a tag."));

            entity.HasIndex(e => new { e.PresentationId, e.TagId }, "unqPresentationTag_PresentationId_TagId").IsUnique();

            entity.Property(e => e.PresentationTagId).HasComment("The identifier of the presentation/tag record.");
            entity.Property(e => e.PresentationId)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasComment("Identifier of the associated presentation.");
            entity.Property(e => e.TagId).HasComment("Identifier of the associated tag.");

            entity.HasOne(d => d.Presentation).WithMany(p => p.PresentationTags)
                .HasForeignKey(d => d.PresentationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fkPresentationTag_Presentation");

            entity.HasOne(d => d.Tag).WithMany(p => p.PresentationTags)
                .HasForeignKey(d => d.TagId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fkPresentationTag_Tag");
        });

        modelBuilder.Entity<PresentationText>(entity =>
        {
            entity.HasKey(e => e.PresentationTextId).HasName("pkcPresentationText");

            entity.ToTable("PresentationText", tb => tb.HasComment("The text for a presentation details in a specific language."));

            entity.HasIndex(e => new { e.PresentationId, e.LanguageCode }, "unqPresentationText_PresentationId_LanguageCode").IsUnique();

            entity.Property(e => e.PresentationTextId).HasComment("The identifier of the presentation text record.");
            entity.Property(e => e.Abstract)
                .HasMaxLength(3000)
                .HasComment("The full abstract for the presentation.");
            entity.Property(e => e.AdditionalDetails).HasMaxLength(3000);
            entity.Property(e => e.ElevatorPitch)
                .HasMaxLength(160)
                .HasComment("The summary for the presentation.");
            entity.Property(e => e.LanguageCode)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.PresentationId)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasComment("The identifier of the associated presentation.");
            entity.Property(e => e.PresentationShortTitle)
                .HasMaxLength(60)
                .HasComment("The short title of the presentation.");
            entity.Property(e => e.PresentationTitle)
                .IsRequired()
                .HasMaxLength(300)
                .HasComment("The full title of the presentation.");
            entity.Property(e => e.ShortAbstract)
                .HasMaxLength(2000)
                .HasComment("The short abstract for the presentation.");

            entity.HasOne(d => d.LanguageCodeNavigation).WithMany(p => p.PresentationTexts)
                .HasForeignKey(d => d.LanguageCode)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fkPresentationText_Language");

            entity.HasOne(d => d.Presentation).WithMany(p => p.PresentationTexts)
                .HasForeignKey(d => d.PresentationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fkPresentationText_Presentation");
        });

        modelBuilder.Entity<PresentationType>(entity =>
        {
            entity.HasKey(e => e.PresentationTypeId).HasName("pkcPresentationType");

            entity.ToTable("PresentationType", tb => tb.HasComment("Represents a type of a presentation."));

            entity.Property(e => e.PresentationTypeId).HasComment("The identifier of the presentation type record.");
            entity.Property(e => e.IsEnabled)
                .HasDefaultValue(true)
                .HasComment("Flag indicating whether the presentation type is enabled.");
            entity.Property(e => e.PresentationTypeName)
                .IsRequired()
                .HasMaxLength(100)
                .HasComment("The name of the presentation type.");
            entity.Property(e => e.SortOrder).HasComment("The sorting order of the presentation type.");
            entity.Property(e => e.TypeDescription)
                .HasMaxLength(500)
                .HasComment("A description of the presentation type.");
        });

        modelBuilder.Entity<Tag>(entity =>
        {
            entity.HasKey(e => e.TagId).HasName("pkcTag");

            entity.ToTable("Tag", tb => tb.HasComment("Represents a label attached to a presentation."));

            entity.Property(e => e.TagId).HasComment("The identifier of the tag record.");
            entity.Property(e => e.IsEnabled)
                .HasDefaultValue(true)
                .HasComment("Flag indicating whether the tag is enabled.");
            entity.Property(e => e.TagName)
                .IsRequired()
                .HasMaxLength(100)
                .HasComment("The name of the tag.");
        });

        modelBuilder.Entity<TimeZone>(entity =>
        {
            entity.HasKey(e => e.TimeZoneId).HasName("pkcTimeZone");

            entity.ToTable("TimeZone", tb => tb.HasComment("Represents the list of time zones as defined by the IANA."));

            entity.Property(e => e.TimeZoneId)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasComment("The identifier of the time zone as defined by the IANA.");
            entity.Property(e => e.DaylightOffset)
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength()
                .HasComment("The daylight offset for the time zone.");
            entity.Property(e => e.DaylightSavingsAbbreviation)
                .HasMaxLength(7)
                .IsUnicode(false)
                .IsFixedLength()
                .HasComment("The daylight savings abbreviation for the time zone.");
            entity.Property(e => e.StandardAbbreviation)
                .IsRequired()
                .HasMaxLength(7)
                .IsUnicode(false)
                .IsFixedLength()
                .HasComment("The standard abbreviation for the time zone.");
            entity.Property(e => e.StandardOffset)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength()
                .HasComment("The standard offset for the time zone.");
        });

        modelBuilder.Entity<WorldRegion>(entity =>
        {
            entity.HasKey(e => e.WorldRegionCode).HasName("pkcWorldRegion");

            entity.ToTable("WorldRegion", tb => tb.HasComment("Lookup table representing the world regions as defined by the UN M49 specification."));

            entity.HasIndex(e => e.ParentId, "idxWorldRegion_ParentId");

            entity.Property(e => e.WorldRegionCode)
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength()
                .HasComment("Identifier of the world region.");
            entity.Property(e => e.IsEnabled).HasComment("Flag indicating whether the world region is enabled.");
            entity.Property(e => e.ParentId)
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength()
                .HasComment("Identifier of the world region parent (for subregions).");
            entity.Property(e => e.WorldRegionName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasComment("Name of the world region.");

            entity.HasOne(d => d.Parent).WithMany(p => p.InverseParent)
                .HasForeignKey(d => d.ParentId)
                .HasConstraintName("fkWorldRegion_WorldRegion");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}