// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hermes.Models;

/// <summary>
/// Represents the status of a speaker&apos;s presentation.
/// </summary>
public partial class PresentationStatus
{
    /// <summary>
    /// The identifier of the presentation status record.
    /// </summary>
    public int PresentationStatusId { get; set; }

    /// <summary>
    /// The name of the presentation status.
    /// </summary>
    public string PresentationStatusName { get; set; }

    /// <summary>
    /// Flag indicating whether the presentation status has been archived.
    /// </summary>
    public bool PresentationIsArchived { get; set; }

    /// <summary>
    /// The order in which the presentation status should be displayed.
    /// </summary>
    public int SortOrder { get; set; }

    /// <summary>
    /// Flag indicating whether the presentation status is enabled.
    /// </summary>
    public bool IsEnabled { get; set; }

    public virtual ICollection<Presentation> Presentations { get; set; } = new List<Presentation>();
}