// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hermes.Models;

/// <summary>
/// Represents the speaker&apos;s presentations.
/// </summary>
public partial class Presentation
{
    /// <summary>
    /// The permament link for the presentation.
    /// </summary>
    public string Permalink { get; set; }

    /// <summary>
    /// Identifier of the type of presentation is represented.
    /// </summary>
    public int PresentationTypeId { get; set; }

    /// <summary>
    /// Identifier of the status of the presentation is represented.
    /// </summary>
    public int PresentationStatusId { get; set; }

    /// <summary>
    /// The link to the public repository for the presentation.
    /// </summary>
    public string PublicRepoLink { get; set; }

    /// <summary>
    /// The link to the private repository for the presentation.
    /// </summary>
    public string PrivateRepoLink { get; set; }

    /// <summary>
    /// The original thumbnail image for the presentation.
    /// </summary>
    public string OriginalThumbnailUrl { get; set; }

    /// <summary>
    /// Flag indicating whether the presentation has been archived.
    /// </summary>
    public bool IsArchived { get; set; }

    /// <summary>
    /// Flag indicating whether the presentation is to be include in the public profile.
    /// </summary>
    public bool IncludeInPublicProfile { get; set; }

    /// <summary>
    /// The default language to use for the presentation.
    /// </summary>
    public string DefaultLanguageCode { get; set; }

    /// <summary>
    /// The resources for the presentation.
    /// </summary>
    public string Resources { get; set; }

    public virtual Language DefaultLanguageCodeNavigation { get; set; }

    public virtual ICollection<EngagementPresentation> EngagementPresentations { get; set; } = new List<EngagementPresentation>();

    public virtual PresentationStatus PresentationStatus { get; set; }

    public virtual ICollection<PresentationTag> PresentationTags { get; set; } = new List<PresentationTag>();

    public virtual ICollection<PresentationText> PresentationTexts { get; set; } = new List<PresentationText>();

    public virtual PresentationType PresentationType { get; set; }
}