// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hermes.Models;

/// <summary>
/// Represents a submission status.
/// </summary>
public partial class SubmissionStatus
{
    /// <summary>
    /// The identifier of the submnission status record.
    /// </summary>
    public int SubmissionStatusId { get; set; }

    /// <summary>
    /// The name of the submission status.
    /// </summary>
    public string SubmissionStatusName { get; set; }

    /// <summary>
    /// The sorting order of the submission status.
    /// </summary>
    public int SortOrder { get; set; }

    /// <summary>
    /// A description of the submission status.
    /// </summary>
    public string StatusDescription { get; set; }

    /// <summary>
    /// Flag indicating whether the submission status is the default status.
    /// </summary>
    public bool IsDefault { get; set; }

    /// <summary>
    /// Flag indicating whether the submission status indicates acceptance.
    /// </summary>
    public bool IndicatesAcceptance { get; set; }

    /// <summary>
    /// Flag indicating whether the submission status is enabled.
    /// </summary>
    public bool IsEnabled { get; set; }

    public virtual ICollection<Submission> Submissions { get; set; } = new List<Submission>();
}