// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hermes.Models;

/// <summary>
/// Associated a tag with a call for speaker submission.
/// </summary>
public partial class SubmissionTag
{
    /// <summary>
    /// Identifier of the SubmissionTag record.
    /// </summary>
    public int SubmissionTagId { get; set; }

    /// <summary>
    /// Identifier of the associated submission.
    /// </summary>
    public int SubmissionId { get; set; }

    /// <summary>
    /// Identifier of the associated tag.
    /// </summary>
    public int TagId { get; set; }

    public virtual Submission Submission { get; set; }

    public virtual Tag Tag { get; set; }
}