// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hermes.Models;

/// <summary>
/// Represents a learning objective that was a part of a submission to a call for speakers..
/// </summary>
public partial class SubmissionLearningObjective
{
    /// <summary>
    /// Identifier of the SubmissionLearningObjective record.
    /// </summary>
    public int SubmissionLearningObjectiveId { get; set; }

    /// <summary>
    /// Identifier of the associated submission record.
    /// </summary>
    public int SubmissionId { get; set; }

    /// <summary>
    /// The text of the submitted learning objective.
    /// </summary>
    public string LearningObjectiveText { get; set; }

    public virtual Submission Submission { get; set; }
}