// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hermes.Models;

/// <summary>
/// Represents a session submission to a call for speakers.
/// </summary>
public partial class Submission
{
    /// <summary>
    /// Identifier of the Submission record.
    /// </summary>
    public int SubmissionId { get; set; }

    /// <summary>
    /// Identifier of the associated call for speakers.
    /// </summary>
    public int CallForSpeakerId { get; set; }

    /// <summary>
    /// Identifier of the status for the submission.
    /// </summary>
    public int SubmissionStatusId { get; set; }

    /// <summary>
    /// The date of the submission.
    /// </summary>
    public DateOnly SubmissionDate { get; set; }

    /// <summary>
    /// The date the event provided a decision about the submission.
    /// </summary>
    public DateOnly? DecisionDate { get; set; }

    /// <summary>
    /// Identifier of the associated presentation.
    /// </summary>
    public int PresentationId { get; set; }

    public string SubmissionLanguageCode { get; set; }

    /// <summary>
    /// The title of the submitted session.
    /// </summary>
    public string SessionTitle { get; set; }

    /// <summary>
    /// The description of the submitted session.
    /// </summary>
    public string SessionDescription { get; set; }

    /// <summary>
    /// The length of the submitted session (in minutes).
    /// </summary>
    public int SessionLength { get; set; }

    /// <summary>
    /// The track the session was submitted under.
    /// </summary>
    public string SessionTrack { get; set; }

    /// <summary>
    /// The level of the submitted session.
    /// </summary>
    public string SessionLevel { get; set; }

    /// <summary>
    /// The elevator pitch for the session.
    /// </summary>
    public string ElevatorPitch { get; set; }

    /// <summary>
    /// Any additional details about the session submission to the event organizers.
    /// </summary>
    public string AdditionalDetails { get; set; }

    public virtual CallForSpeaker CallForSpeaker { get; set; }

    public virtual Presentation Presentation { get; set; }

    public virtual ICollection<SubmissionLearningObjective> SubmissionLearningObjectives { get; set; } = new List<SubmissionLearningObjective>();

    public virtual SubmissionStatus SubmissionStatus { get; set; }

    public virtual ICollection<SubmissionTag> SubmissionTags { get; set; } = new List<SubmissionTag>();
}