:r .\Populate\Populate_Language.sql
:r .\Populate\Populate_PresentationType.sql
:r .\Populate\Populate_PresentationStatus.sql
:r .\Populate\Populate_CallForSpeakerStatus.sql
:r .\Populate\Populate_WorldRegion.sql
:r .\Populate\Populate_Country.sql
:r .\Populate\Populate_CountryDivision.sql
:r .\Populate\Populate_TimeZone.sql
:r .\Populate\Populate_SubmissionStatus.sql
:r .\Populate\Populate_EngagementType.sql
:r .\Populate\Populate_EngagementStatus.sql
:r .\Populate\Populate_EngagementPresentationStatus.sql
:r .\Populate\Populate_EngagementCallForSpeakerStatus.sql